### ISSUE TITLE
sed: character class syntax is [[:space:]], not [:space:]

### ISSUE THREAD

**Issue by cunneen** [fink/scripts#45]
`srcinstaller/Install Fink.tool`

There seems a problem with syntax in the makefile of `dpkg-bootstrap` . NB: I upgraded to the latest Mac OS 10.13.5 yesterday, I'm not sure if that's related. 

My output:

```
gcc -L/sw/bootstrap/lib -L../lib -L../optlib -framework CoreFoundation  -o dpkg-split  queue.o  split.o  info.o  join.o  main.o -ldpkg -lopt  
/Applications/Xcode_9.3.app/Contents/Developer/usr/bin/make  -C "scripts" "all"
sed -e "s:^#![:space:]*/usr/bin/perl:#! /usr/bin/perl:; \
		s:\$dpkglibdir[[:space:]]*=[[:space:]]*['\"][^'\"]*['\"]:\$dpkglibdir=\"/sw/bootstrap/lib/dpkg\":; \
		s:\$admindir[[:space:]]*=[[:space:]]*['\"][^'\"]*['\"]:\$admindir=\"/sw/var/lib/dpkg\":; \
		s:\$version[[:space:]]*=[[:space:]]*['\"][^'\"]*[\"']:\$version=\"1.10.21\":" \
		< cl-debian.pl > cl-debian
sed: character class syntax is [[:space:]], not [:space:]
make[2]: *** [cl-debian] Error 4
make[1]: *** [all-scripts] Error 2
make: *** [all-recursive] Error 2
### execution of make failed, exit code 2
phase compiling: dpkg-bootstrap-1.10.21-1221 failed
```

**Comment by nieder** [comment]
What's the output of `which sed`?

**Comment by cunneen** [comment]
```
$ which sed
/usr/bin/sed

```

**Comment by dak180** [comment]
@nieder this is in `dpkg-bootstrap` not `Install Fink.tool`, all it does is run `./bootstrap /sw`.

**Comment by dmacks** [comment]
I thought our .info hardcoded use of "/usr/bin/sed", but the error transcript is just using "sed". But as to the error itself, it's indeed an upstream dpkg error; we should just import [their patch](https://salsa.debian.org/dpkg-team/dpkg/commit/eaa28ebd958001ed54a96844c90f4bf900386de3) to switch to double brackets. I was able to get a few other mis/failed builds due to a ton of bad -I ordering and -L problems, but that can wait for another day.

**Comment by akhansen** [comment]
dpkg.info hardcodes /usr/bin/sed, but dpkg-bootstrap.info appears not to have been updated to do so.

**Comment by akhansen** [comment]
Closing because of dpkg build change noted above.
